---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/sidqtech.com/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --exclude='.env' --exclude='.env.*' --exclude='.git*' --exclude='.cpanel.yml' ./ $DEPLOYPATH
